#!/bin/sh
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# TODO: handle $DOTFILES_PATH not set on first install
# TODO: move into dotfiles folder
export ZDOTDIR=$DOTFILES_PATH/zsh
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

./install_brews
# Install vim-plug for neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim  -c "PlugInstall" -c "qa"

mkdir -p ~/.vim/colors

git config --global core.editor $(which nvim)
git config --global core.excludesfile "$PWD"/.gitignore
git config --global rerere.enabled true
git config --global alias.g "grep --break --heading --line-number"

# Vim colors
mkdir ~/.config/nvim/colors

cp color-schemes/railscasts/base16-railscasts.vim ~/.config/nvim/colors
cp color-schemes/lucius/lucius.vim ~/.config/nvim/colors

# Iterm colors
open color-schemes/railscasts/base16-railscasts.dark.256.itermcolors
open color-schemes/lucius/LuciusLight.itermcolors

# Iterm preferences
# http://stratus3d.com/blog/2015/02/28/sync-iterm2-profile-with-dotfiles-repository/
# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$PWD"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

pip3 install neovim
bundle install
xcode-select --install
npm install -g livedown

echo "---"
echo "Please link your dotfiles:"
printf "ln -s $DOTFILES_PATH/zsh/zshrc $DOTFILES_PATH/zsh/.zshrc"
printf "ln -s $DOTFILES_PATH/zsh/zshrc ~/.zshrc"
printf "ln -s $DOTFILES_PATH/tmux_conf ~/.tmux.conf"
printf "ln -s $DOTFILES_PATH/tigrc ~/.tigrc"
printf "ln -s $DOTFILES_PATH/vim/vimrc ~/.config/nvim/init.vim"
printf "ln -s $DOTFILES_PATH/zsh/.ctags ~/.ctags"
printf "ln -s $DOTFILES_PATH/alacritty.yml ~/.alacritty.yml"
echo "---"
echo "If your shell looks weird, install_powerline_fonts.sh is your friend."
