#!/bin/bash
omnisharpVersion="v1.35.3"
mkdir -p $HOME/.omnisharp && \
    curl -Lo /tmp/omnisharp-roslyn.tar.gz \
    "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/$omnisharpVersion/omnisharp-linux-x64.tar.gz" && \
    tar -xzf /tmp/omnisharp-roslyn.tar.gz -C $HOME/.omnisharp && \
    rm /tmp/omnisharp-roslyn.tar.gz
# Use bundled mono
export PATH="$PATH:$HOME/.omnisharp/bin"
