#!/bin/bash
# reset all tmux settings
tmux source-file ~/dotfiles/tmux/tmux-reset
# Load user settings
tmux source-file "$1"
#tmux refresh-client -S
tmux new-window "VIMUSER=$2 nvim -S $3 -u $4"
#tmux send-keys -t left "VIMUSER=$2 nvim -S $3 -u $4" Enter
