### Exports ###
export DOTFILES_PATH=~/dotfiles
export ZDOTDIR="$DOTFILES_PATH/zsh"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
 export EDITOR='vim'
else
 export EDITOR='nvim'
fi
# fzf
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND="rg --files --hidden"
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export KEYTIMEOUT=1
export DOTNET_CLI_TELEMETRY_OPTOUT=true
# Installed via homebrew.
# Hardcoded because `brew --prefix` takes a long time.
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/neovim/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="$DOTFILES_PATH/bin:$PATH"
export PATH="/usr/local/opt/ctags/bin:$PATH"
PATH=$PATH:/usr/local/bin
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
# Rbenv
# Directory for tmuxinator configurations
export TMUXINATOR_CONFIG="$DOTFILES_PATH/tmuxinator"

export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

### Aliases ###
alias be="bundle exec"
alias bel="BUNDLE_GEMFILE=Gemfile.local bundle exec"
alias colours='for i in {0..255}; do printf "\x1b[38;5;${i}mcolor%-5i\x1b[0m" $i ; if ! (( ($i + 1 ) % 8 )); then echo ; fi ; done'
alias cop="bundle exec rubocop --rails --display-cop-names"
alias ctags="/usr/local/opt/ctags/bin/ctags"
alias dc="bin/compose local development"
alias dcu="dc pull && dc down && dc up"
alias del_vim_swaps='find ~/.vim/ -type f -name "*.sw[klmnop]" -delete'
alias disable_mouse_accel='defaults write .GlobalPreferences com.apple.mouse.scaling -1'
alias dps="docker ps --format '{{.Names}}'"
alias flushdns="sudo -- sh -c 'killall -HUP mDNSResponder; killall mDNSResponderHelper; dscacheutil -flushcache; arp -ad'"
alias g="git"
alias gd="git diff"
alias gitzip='git archive HEAD -o ${PWD##*/}.zip'
# Previously gs would start GhostScript
alias gs="git status"
alias gp="git push"
alias gpf="git push --force-with-lease"
# Project specific branches
alias gp2="git push origin $(git rev-parse --abbrev-ref HEAD):stage2 --force"
alias gp3="git push origin $(git rev-parse --abbrev-ref HEAD):stage3 --force"
alias kill_mars="docker ps --filter 'name=mars_' -q | xargs docker stop"
alias rc="bundle exec rails console"
alias rs="bundle exec rails server"
alias tags="ctags -R --exclude=.git --exclude=data --exclude=docker --exclude=coverage --exclude=node_modules --exclude=tmp --exclude=log --exclude=public --exclude=assets --exclude=*.sql"
alias originalrc="/usr/bin/rs"
alias vi="nvim"
alias vim="nvim"

### Keybindings ###
# https://dougblack.io/words/zsh-vi-mode.html
# vi mode instead of emacs mode
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

### Functions ###
source "$DOTFILES_PATH/bin/mutest.sh"

# always ls after cd
function cd() {
    new_directory="$*";
    if [ $# -eq 0 ]; then
        new_directory=${HOME};
    fi;
    builtin cd "${new_directory}" && ls
}

function zle-line-init zle-keymap-select {
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $EPS1"
    zle reset-prompt
}

### Misc ###
# Better colors
TERM="xterm-256color"
# Hide user/hostname
DEFAULT_USER=$USER
zle -N zle-line-init
zle -N zle-keymap-select

# Init zprezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Tmuxinator autocompletion
source "$DOTFILES_PATH/tmuxinator/tmuxinator.zsh"

# kubectl autocompletion
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi

# init fzf
# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/share/bash-completion/completions/fzf" 2> /dev/null

# Key bindings
# ------------
source "$DOTFILES_PATH/fzf/key-bindings.zsh"
