### Exports ###
export DOTFILES_PATH=$HOME/dotfiles
export ZDOTDIR="$DOTFILES_PATH/zsh"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export BROWSER=w3m
# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
 export EDITOR='vim'
else
 export EDITOR='nvim'
fi
# fzf
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND="rg --files --hidden"
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export KEYTIMEOUT=1
export DOTNET_CLI_TELEMETRY_OPTOUT=true
export DOTNET_ROOT=$HOME/dotnet
# Installed via homebrew.
# Hardcoded because `brew --prefix` takes a long time.
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/neovim/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="$DOTFILES_PATH/bin:$PATH"
export PATH="/usr/local/opt/ctags/bin:$PATH"
PATH=$PATH:/usr/local/bin
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/dotnet"
export PATH="$PATH:$HOME/dotnet/tools"
export PATH="$HOME/.omnisharp/bin:$PATH"
# Rbenv
# Directory for tmuxinator configurations
export TMUXINATOR_CONFIG="$DOTFILES_PATH/tmuxinator"
# Use vcXsrv for gui applications
export DISPLAY=$(ip route | awk '{print $3; exit}'):0

### Aliases ###
alias be="bundle exec"
alias colours='for i in {0..255}; do printf "\x1b[38;5;${i}mcolor%-5i\x1b[0m" $i ; if ! (( ($i + 1 ) % 8 )); then echo ; fi ; done'
alias cop="bundle exec rubocop --rails --display-cop-names"
alias ctags="/usr/local/opt/ctags/bin/ctags"
alias dc="bin/compose local development"
alias dcu="dc pull && dc down && dc up"
alias del_vim_swaps='find ~/.vim/ -type f -name "*.sw[klmnop]" -delete'
alias disable_mouse_accel='defaults write .GlobalPreferences com.apple.mouse.scaling -1'
alias dps="docker ps --format '{{.Names}}'"
alias flushdns="sudo -- sh -c 'killall -HUP mDNSResponder; killall mDNSResponderHelper; dscacheutil -flushcache; arp -ad'"
alias g="git"
alias gd="git diff"
alias gitzip='git archive HEAD -o ${PWD##*/}.zip'
# Previously gs would start GhostScript
alias gs="git status"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias remount="sudo mount -t drvfs C: /mnt/c"
alias repos="cd /mnt/c/Users/beckerph/Source/Repos"
alias settings="vim /mnt/c/Users/beckerph/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
alias tags="ctags -R --exclude=.git --exclude=data --exclude=docker --exclude=coverage --exclude=node_modules --exclude=tmp --exclude=log --exclude=public --exclude=assets --exclude=*.sql"
alias originalrc="/usr/bin/rs"
alias vi="nvim"
alias vim="nvim"

### Keybindings ###
# https://dougblack.io/words/zsh-vi-mode.html
# vi mode instead of emacs mode
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

### Functions ###
source "$DOTFILES_PATH/bin/mutest.sh"

# always ls after cd
function cd() {
    new_directory="$*";
    if [ $# -eq 0 ]; then
        new_directory=${HOME};
    fi;
    builtin cd "${new_directory}" && ls
}

function zle-line-init zle-keymap-select {
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $EPS1"
    zle reset-prompt
}

### Misc ###
# Better colors
#TERM="xterm-256color"
# Hide user/hostname
DEFAULT_USER=$USER
zle -N zle-line-init
zle -N zle-keymap-select

# Init zprezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Fix zprezto? stuff
#unalias ls ln

# Tmuxinator autocompletion
source "$DOTFILES_PATH/tmuxinator/tmuxinator.zsh"

# newsboat
function start_newsboat {
  if [ ! -f "$HOME/.newsboat/config" ]; then
    echo "Setting up newsboat..."
    mkdir "$HOME/.newsboat"
    ( cd ~/.newsboat && git init && git remote add origin git@github.com:p-becker/newsboat_config.git && git pull origin master )
  fi
  /usr/sbin/newsboat
}
alias newsboat=start_newsboat

# ssh agent
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
  echo "Initialising new SSH agent..."
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo succeeded
  chmod 600 "${SSH_ENV}"
  . "${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" > /dev/null
  #ps ${SSH_AGENT_PID} doesn't work under cywgin
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent;
  }
else
  start_agent;
fi

# init fzf
[ -f $DOTFILES_PATH/fzf/.fzf.zsh ] && source $DOTFILES_PATH/fzf/.fzf.zsh
